### ISSUE TITLE
Fhempy server offline

### ISSUE THREAD

**Issue by maartenvullings** [dominikkarall/fhempy#69]
Hello,

I have a problem with the fhempy server staying offline. 

Yesterday I updated my raspbian jessie (8) tot 9, then from 9 to 10, and finally from 10 to 11. I did this because I wanted to install Python 3 and that didn't work anymore on version 8 (this version is obsolete). So currently I'm running Rasbian 11. My FHEM is still running okay. So far so good. 

So I installed Python version 3.7 like the instruction: 
https://github.com/dominikkarall/fhempy/blob/master/README.md

Then I entered the instructions in FHEM: 

1. update add https://raw.githubusercontent.com/dominikkarall/fhempy/master/controls_pythonbinding.txt
2. update
3. define fhempy_local BindingsIo fhempy

So now the fhempyserver won't go online (stays red). Fhempylocal is green. See the picture:
![image](https://user-images.githubusercontent.com/100911185/156720113-77407742-ff97-4e96-8a1b-3de2838e0c94.png)

This is what the fhempy log file shows:
![image](https://user-images.githubusercontent.com/100911185/156719885-764bc14a-c6f8-44d0-bf99-2e556b3e4ef9.png)

What can I do to solve the problem?

**Comment by dominikkarall** [comment]
Thx for opening this issue! It was caused by a commit I did yesterday.
Please do a FHEM update followed by a restart. I just released a fix for that issue.

**Comment by maartenvullings** [comment]
So I just did the FHEM update and I saw some files were updated. But now, FHEM won't restart and I can't get into the interface.... I restarted raspbian a few times but still I can't get into FHEM.

**Comment by dominikkarall** [comment]
Please provide fhem and fhempy logs.

**Comment by maartenvullings** [comment]
this is the Femph log:

![image](https://user-images.githubusercontent.com/100911185/156811879-a0955849-b54b-4b35-9543-7809702176eb.png)

FHEM logs:
around 18:03 

![image](https://user-images.githubusercontent.com/100911185/156812872-73e6f4bc-d6c9-4582-99d8-2a949b98f488.png)

and around 18:12:

![image](https://user-images.githubusercontent.com/100911185/156812974-ab0948f0-af21-44a2-b710-d64da473d9e1.png)

**Comment by dominikkarall** [comment]
Found another bug...I just fixed it. Can you please do another update? If you can't access the FHEM web, you can download the file here
https://raw.githubusercontent.com/dominikkarall/fhempy/master/FHEM/10_fhempyServer.pm
and put it in the /opt/fhem/FHEM directory.

**Comment by maartenvullings** [comment]
So I downloaded your file and replaced the file in het directory. Did a restart. But still can't reach the FHEM interface. 

here's the FHEM log:

![image](https://user-images.githubusercontent.com/100911185/156816480-68ef7b38-4dbd-40fe-9733-406956c6f399.png)


here's the Fhempy log:
![image](https://user-images.githubusercontent.com/100911185/156816621-aa593238-0be3-4cf8-8d83-e21ec16747ae.png)

**Comment by dominikkarall** [comment]
it looks like you didn't replace the file correctly. There is call to "main::hempyServer..." instead of "main::fhempyServer". That was the fix. Please check again if you correctly replaced the file in /opt/fhem/FHEM/

**Comment by maartenvullings** [comment]
you are right, had a problem with the authorization to copy files. So I replaced it right now and I can get in FHEM again! Great! 

So what should I do to get the fhempy server running?

**Comment by dominikkarall** [comment]
isn't it running already? If not, replace the file
/opt/fhem/FHEM/bindings/python/bin/fhempy
with this one
https://raw.githubusercontent.com/dominikkarall/fhempy/master/FHEM/bindings/python/bin/fhempy

**Comment by maartenvullings** [comment]
somehow the fempy server is gone now.

![image](https://user-images.githubusercontent.com/100911185/156818527-6594a011-da95-4339-adc5-4289dc8b23ed.png)


Should I reinstall everything?

**Comment by dominikkarall** [comment]
Yes, makes sense to delete and define it again

**Comment by maartenvullings** [comment]
I tried to reinstall everything but the server didn't come up that way... 

So I want to replace the fhempy file. Filezilla says access denied when I want to replace the fhempy file. Could it be in use by FHEM?

**Comment by maartenvullings** [comment]
When I try to do an update in FHEM I get this:

![image](https://user-images.githubusercontent.com/100911185/156821433-a31f2b5c-8338-4320-9fab-8abd00293124.png)

**Comment by dominikkarall** [comment]
You need to correct the permission to the user fhem for the file. If you don't know how to do that you can delete the file and do an update

**Comment by maartenvullings** [comment]
So I deleted the file (SSH: sudo rm fhempy). But I can't copy fhe fhempy file from my hard drive in filezilla to the directory /opt/fhem/FHEM/bindings/python/bin/fhempy

So when I do an update in FHEM (hoping the file would come back) I still get this message:

![image](https://user-images.githubusercontent.com/100911185/156823887-fadd6675-c7ae-48f0-8ce8-3e961b72c84b.png)

**Comment by maartenvullings** [comment]
Okay so I copied the file (by using sudo I managed to do so). Did also an update but still something is not right. 

This is the fhempy log
![image](https://user-images.githubusercontent.com/100911185/156826294-06e7102d-3833-4cd5-b767-99159993dd38.png)


This is the FHEM log
![image](https://user-images.githubusercontent.com/100911185/156826494-17430dba-6a35-4358-b385-4b62b442ccdf.png)

**Comment by maartenvullings** [comment]
Okay so I'm a bit new to this. Sorry for that. 

I changed the ownership of the file /opt/fhem/FHEM/bindings/python/bin/fhempy. Did the following:

sudo chmod +rwx fhempy
sudo chown fhem fhempy

did a reboot
did an update in FHEM

still no server coming up... :-( 

What can I do?

**Comment by maartenvullings** [comment]
could this be the problem? the owner of the file 10_fhempyServer.pm is different than all other files:

![image](https://user-images.githubusercontent.com/100911185/156831063-a9142c1c-a5e1-464a-8a93-8e54030c61c6.png)


Should I change this by:
sudo chown fhem dialout 10_fhempyServer.pm 
?

**Comment by retikulumx** [comment]
`sudo chown fhem:dialout 10_fhempyServer.pm`
or
`sudo chown -R  fhem:dialout /opt/fhem/FHEM/`
to change the ownershow for alle the files inside this folder

**Comment by maartenvullings** [comment]
Okay, I tried to set the ownerships right, but the fhempyserver was still not being created in FHEM after an update. 

Then I deleted the following files:

/opt/fhem/FHEM/10_fhempy.pm
/opt/fhem/FHEM/10_fhempyServer.pm
/opt/fhem/FHEM/bindings/python/bin/fhempy

then I did another update in FHEM. All the files are being created again. But still the fhempyserver won't show in FHEM. 

What commands should I give in FHEM to create the fhempyserver in FHEM? The local fhempy server is created by:
define fhempy_local BindingsIo fhempy

Thanks for all the help so far...

**Comment by retikulumx** [comment]
Yeah, I also have problems running the fhempy server since the last update (I guess).
I deleted the fhempy device and re-defined it and I also tried the fhempy bin you attached above. 
The error would be:

`PERL WARNING: Subroutine fhempyServer_Initialize redefined at ./FHEM/10_fhempyServer.pm line 16.
2022.03.05 10:10:35 1: PERL WARNING: Subroutine fhempyServer_detailFn redefined at ./FHEM/10_fhempyServer.pm line 36.
2022.03.05 10:10:35 1: PERL WARNING: Subroutine fhempyServer_getCmd redefined at ./FHEM/10_fhempyServer.pm line 53.
2022.03.05 10:10:35 1: PERL WARNING: Variable "$hash" is not imported at ./FHEM/10_fhempyServer.pm line 67.
2022.03.05 10:10:35 1: PERL WARNING: Variable "$hash" is not imported at ./FHEM/10_fhempyServer.pm line 74.
2022.03.05 10:10:35 1: PERL WARNING: "my" variable $hash masks earlier declaration in same scope at ./FHEM/10_fhempyServer.pm line 130.
2022.03.05 10:10:35 1: PERL WARNING: "state" variable @_ masks earlier declaration in same scope at ./FHEM/10_fhempyServer.pm line 130.
2022.03.05 10:10:35 1: reload: Error:Modul 10_fhempyServer deactivated:
 syntax error at ./FHEM/10_fhempyServer.pm line 63, near ") {"
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/10_fhempyServer.pm line 67.
Global symbol "$ver" requires explicit package name (did you forget to declare "my $ver"?) at ./FHEM/10_fhempyServer.pm line 67.
syntax error at ./FHEM/10_fhempyServer.pm line 69, near "}"
Can't use global @_ in "my" at ./FHEM/10_fhempyServer.pm line 73, near "= @_"
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/10_fhempyServer.pm line 74.
syntax error at ./FHEM/10_fhempyServer.pm line 126, near "}"
Can't use global @_ in "my" at ./FHEM/10_fhempyServer.pm line 130, near "= @_"
Global symbol "$dev" requires explicit package name (did you forget to declare "my $dev"?) at ./FHEM/10_fhempyServer.pm line 132.
syntax error at ./FHEM/10_fhempyServer.pm line 142, near "}"
./FHEM/10_fhempyServer.pm has too many errors.

2022.03.05 10:10:35 0: syntax error at ./FHEM/10_fhempyServer.pm line 63, near ") {"
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/10_fhempyServer.pm line 67.
Global symbol "$ver" requires explicit package name (did you forget to declare "my $ver"?) at ./FHEM/10_fhempyServer.pm line 67.
syntax error at ./FHEM/10_fhempyServer.pm line 69, near "}"
Can't use global @_ in "my" at ./FHEM/10_fhempyServer.pm line 73, near "= @_"
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/10_fhempyServer.pm line 74.
syntax error at ./FHEM/10_fhempyServer.pm line 126, near "}"
Can't use global @_ in "my" at ./FHEM/10_fhempyServer.pm line 130, near "= @_"
Global symbol "$dev" requires explicit package name (did you forget to declare "my $dev"?) at ./FHEM/10_fhempyServer.pm line 132.
syntax error at ./FHEM/10_fhempyServer.pm line 142, near "}"
./FHEM/10_fhempyServer.pm has too many errors.`

I might be missing something.

Oh and I'm still on Buster.

**Comment by retikulumx** [comment]
Nevermind. I solved the problem by running the fhempy binary from a terminal. It then reinstalled all modules, started and it's running.

```
`sudo ./fhempy

2022-03-05 10:39:26,531 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "./fhempy", line 100, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2022-03-05 10:39:26,534 - INFO     - __main__: Attempting install of fhempy>=0.1.12
2022-03-05 10:40:17,552 - INFO     - __main__: Successfully installed fhempy>=0.1.12
2022-03-05 10:40:18,708 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-05 10:40:18,740 - INFO     - fhempy.lib.pkg_installer: Attempting install of async-upnp-client==0.20.0
2022-03-05 10:40:28,108 - INFO     - fhempy.lib.pkg_installer: Successfully installed async-upnp-client==0.20.0 update!
2022-03-05 10:40:28,113 - INFO     - fhempy.lib.fhem_pythonbinding: Advertise fhempy on local network
2022-03-05 10:40:28,523 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-05 10:40:28,639 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2022-03-05 10:40:31,027 - INFO     - websockets.server: connection open`
```

**Comment by dominikkarall** [comment]
Please do another update within FHEM, it should update 10_fhempyServer.pm which should work again.

**Comment by maartenvullings** [comment]
Okay I did the update and I'm one step closer to getting it working. :-) The server is shown in the FHEM interface and it's green:

![image](https://user-images.githubusercontent.com/100911185/156892138-6c559346-70e4-4c1f-b8f8-3e159bb05638.png)

So I defined the Nefit easy thermostat

define nefit_thermostat fhempy nefit <SERIAL_NUMBER>
attr nefit_thermostat access_key <ACCEESS_KEY>
attr nefit_thermostat password <PASSWORD>

But then the nefit device still says the server is offline:

![image](https://user-images.githubusercontent.com/100911185/156892199-c7d10e03-fbc7-4222-8746-f787a3821103.png)

The fhempyserver shows this:

![image](https://user-images.githubusercontent.com/100911185/156892229-13908f02-c06c-4409-bd08-43541a9d5f77.png)

State shows: ???

this is what the fhempy log shows:

2022-03-05 17:08:30,049 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-05 17:08:30,067 - INFO     - fhempy.lib.pkg_installer: Attempting install of async-upnp-client==0.20.0
2022-03-05 17:08:42,863 - INFO     - fhempy.lib.pkg_installer: Successfully installed async-upnp-client==0.20.0 update!
2022-03-05 17:08:42,866 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-05 17:08:42,998 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x75129a48>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.132 seconds
2022-03-05 17:08:43,002 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2022-03-05 17:13:24,249 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-05 17:13:24,280 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-05 17:13:24,420 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7589a730>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.171 seconds
2022-03-05 17:13:24,423 - INFO     - websockets.server: server listening on 0.0.0.0:15733

Why does the nefit device still says the fhempyserver is offline?

**Comment by maartenvullings** [comment]
It's online! Did another reboot after defining the nefit device:

![image](https://user-images.githubusercontent.com/100911185/156892371-c2a26412-bbea-4719-8a67-68a229525be8.png)

Also the nefit device is connected:

![image](https://user-images.githubusercontent.com/100911185/156892455-11eee474-4272-48cd-8b36-214bbc5f86ef.png)

However, changing the temperature is not coming through on my Nefit easy device or the Nefit app... Hmmmm....

**Comment by dominikkarall** [comment]
Nefit should also show you some readings after connected. Have you checked the fhempy log? Serial number, access_key and password is correct?

**Comment by maartenvullings** [comment]
I removed the Nefit device. Created it againg. Did an update in FHEM. And now the fhempy_local is hanging in "update started":

![image](https://user-images.githubusercontent.com/100911185/156914944-939f4040-fa82-4863-a426-ddab3b943626.png)


![image](https://user-images.githubusercontent.com/100911185/156914917-269eb470-6a67-4cbd-8ad7-4a8d760e57ef.png)


This is what the FHEM log shows after the update:
2022-03-05 17:08:30,049 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-05 17:08:30,067 - INFO     - fhempy.lib.pkg_installer: Attempting install of async-upnp-client==0.20.0
2022-03-05 17:08:42,863 - INFO     - fhempy.lib.pkg_installer: Successfully installed async-upnp-client==0.20.0 update!
2022-03-05 17:08:42,866 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-05 17:08:42,998 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x75129a48>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.132 seconds
2022-03-05 17:08:43,002 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2022-03-05 17:13:24,249 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-05 17:13:24,280 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-05 17:13:24,420 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7589a730>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.171 seconds
2022-03-05 17:13:24,423 - INFO     - websockets.server: server listening on 0.0.0.0:15733







This is the last fhempy log (from yesterday):

2022-03-05 17:08:30,049 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-05 17:08:30,067 - INFO     - fhempy.lib.pkg_installer: Attempting install of async-upnp-client==0.20.0
2022-03-05 17:08:42,863 - INFO     - fhempy.lib.pkg_installer: Successfully installed async-upnp-client==0.20.0 update!
2022-03-05 17:08:42,866 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-05 17:08:42,998 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x75129a48>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.132 seconds
2022-03-05 17:08:43,002 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2022-03-05 17:13:24,249 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-05 17:13:24,280 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-05 17:13:24,420 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x7589a730>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.171 seconds
2022-03-05 17:13:24,423 - INFO     - websockets.server: server listening on 0.0.0.0:15733

**Comment by maartenvullings** [comment]
Seems like the fhempy_local has problems coming back online after a restart of FHEM. When I restart the fhempyserver, the local server comes back online and also the nefit device will connect again. But still something not right because the Nefit device is not working properly (no readings and can't set the temp).

Now the fhempy log shows this:

2022-03-06 09:18:57,172 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-06 09:18:57,205 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-06 09:18:57,342 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x758ee880>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.170 seconds
2022-03-06 09:18:57,345 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2022-03-06 09:19:14,167 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy...
2022-03-06 09:19:14,189 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2022-03-06 09:19:14,274 - WARNING  - asyncio: Executing <Task pending name='Task-1' coro=<async_main() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:498> wait_for=<_GatheringFuture pending cb=[<TaskWakeupMethWrapper object at 0x75889880>()] created at /usr/lib/python3.9/asyncio/tasks.py:704> cb=[_run_until_complete_cb() at /usr/lib/python3.9/asyncio/base_events.py:184] created at /usr/lib/python3.9/asyncio/base_events.py:621> took 0.107 seconds
2022-03-06 09:19:14,277 - INFO     - websockets.server: server listening on 0.0.0.0:15733
2022-03-06 09:19:23,634 - INFO     - websockets.server: connection open
2022-03-06 09:19:23,637 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 127.0.0.1
2022-03-06 09:19:23,812 - WARNING  - slixmpp.stringprep: Using slower stringprep, consider compiling the faster cython/libidn one.
2022-03-06 09:19:24,683 - WARNING  - asyncio: Executing <Task pending name='Task-36' coro=<nefit.nefit_connect() running at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/nefit/nefit.py:417> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x74cb5580>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> created at /usr/lib/python3.9/asyncio/tasks.py:361> took 0.182 seconds
2022-03-06 09:19:25,529 - INFO     - slixmpp.features.feature_bind.bind: JID set to: rrccontact_560954402@wa2-mz36-qrmzh6.bosch.de/8u8fjjab68
2022-03-06 09:19:25,940 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:26,070 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:26,233 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:26,375 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:26,501 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:26,629 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:26,762 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:26,898 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,021 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,147 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,273 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,405 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,534 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,659 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,799 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:27,924 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:28,050 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:28,179 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:28,307 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:28,432 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:28,564 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:28,692 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:28,822 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,005 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,078 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,208 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,333 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,466 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,601 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,730 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,851 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:29,973 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,106 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,233 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,360 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,491 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,620 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,740 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,868 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:30,993 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:31,120 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:31,247 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:31,382 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:19:31,524 - ERROR    - aionefit: Error decrypting message. Password incorrect?
2022-03-06 09:21:41,282 - INFO     - slixmpp.features.feature_bind.bind: JID set to: rrccontact_560954402@wa2-mz36-qrmzh6.bosch.de/9gd09lcdpp
2022-03-06 09:21:41,283 - ERROR    - slixmpp.basexmpp: There is already a scheduled event of name: Whitespace Keepalive
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 846, in event
    handler_callback(data)
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 637, in _start_keepalive
    self.schedule('Whitespace Keepalive',
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 875, in schedule
    raise ValueError(
ValueError: There is already a scheduled event of name: Whitespace Keepalive
2022-03-06 09:24:26,491 - INFO     - slixmpp.xmlstream.xmlstream: connection_lost: (None,)
2022-03-06 09:24:26,501 - INFO     - slixmpp.xmlstream.xmlstream: connection_lost: (None,)
2022-03-06 09:24:37,336 - INFO     - slixmpp.features.feature_bind.bind: JID set to: rrccontact_560954402@wa2-mz36-qrmzh6.bosch.de/20w3m8u3er
2022-03-06 09:24:46,430 - INFO     - slixmpp.features.feature_bind.bind: JID set to: rrccontact_560954402@wa2-mz36-qrmzh6.bosch.de/2dz01h7gdb
2022-03-06 09:24:46,431 - ERROR    - slixmpp.basexmpp: There is already a scheduled event of name: Whitespace Keepalive
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 846, in event
    handler_callback(data)
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 637, in _start_keepalive
    self.schedule('Whitespace Keepalive',
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 875, in schedule
    raise ValueError(
ValueError: There is already a scheduled event of name: Whitespace Keepalive
2022-03-06 09:25:25,477 - INFO     - slixmpp.features.feature_bind.bind: JID set to: rrccontact_560954402@wa2-mz36-qrmzh6.bosch.de/8pugdr8fe5
2022-03-06 09:25:25,478 - ERROR    - slixmpp.basexmpp: There is already a scheduled event of name: Whitespace Keepalive
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 846, in event
    handler_callback(data)
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 637, in _start_keepalive
    self.schedule('Whitespace Keepalive',
  File "/opt/fhem/.local/lib/python3.9/site-packages/slixmpp/xmlstream/xmlstream.py", line 875, in schedule
    raise ValueError(
ValueError: There is already a scheduled event of name: Whitespace Keepalive

**Comment by maartenvullings** [comment]
The Nefit device is working. There was indeed a password typo....

However when restarting FHEM, I still have to manually restart the fhempyserver in order to get the fhempy_local running...

**Comment by dominikkarall** [comment]
Please use code tags!

```
2022-03-06 09:19:25,940 - ERROR - aionefit: Error decrypting message. Password incorrect?
```
I think that error message is clear?

**Comment by dominikkarall** [comment]
> The Nefit device is working. There was indeed a password typo....
> 
> However when restarting FHEM, I still have to manually restart the fhempyserver in order to get the fhempy_local running...

It might take up to a minute until fhempy_local connects. Please provide the FHEM log - in code tags!

**Comment by retikulumx** [comment]
Hi.
Same here, the fhempy_local stays offline until I manually restart the server component. The Fhem log just throws this over and over again (verbose 5):

```
2022.03.06 10:49:10 4: HttpUtils: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.03.06 10:49:10 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.03.06 10:49:21 5: HttpUtils url=http://127.0.0.1:15733/ NonBlocking via http
2022.03.06 10:49:21 4: IP: 127.0.0.1 -> 127.0.0.1
```

After the manual restart of the server component:

```
2022.03.06 11:04:35 5: HttpUtils request header:
GET / HTTP/1.1
Host: 127.0.0.1:15733
User-Agent: fhem
Accept-Encoding: gzip,deflate
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: s8UvXgMPglOWJRR3PI68/Q==
Sec-WebSocket-Version: 13

2022.03.06 11:04:35 4: http://127.0.0.1:15733/: HTTP response code 101
2022.03.06 11:04:35 5: HttpUtils http://127.0.0.1:15733/: Got data, length: 0
2022.03.06 11:04:35 5: HttpUtils response header:
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: Ldewgo54rIXsEKknDJL7qRaQJSc=
Date: Sun, 06 Mar 2022 10:04:35 GMT
Server: Python/3.7 websockets/10.0
```

and then it finally starts doing its job.

**Comment by dominikkarall** [comment]
You are right, thx for pointing that out!

I just fixed it, it should automatically start after FHEM restart again. Please do a FHEM update.

**Comment by retikulumx** [comment]
Yes, it seems working now.
Thanks very much for the quick fix, Dominik.

Have a great sunday!

**Comment by dominikkarall** [comment]
Thanks for the reply! Unfortunately that update was a little bit a mess :/ I hope I can prevent such issues in the future...

**Comment by maartenvullings** [comment]
Here also everything works nog. After a restart the the server also starts. 

@retikulumx and @dominikkarall Thanks for the help! Great work.

**Comment by maartenvullings** [comment]
Hi fhempy, 

I have the same problem again. The Fhempy server stays offline. I deleted the fhempy server and the fhempy local, did FHEM update and restart. Created the Fhempy server in FHEM again, but it stays offline:

![image](https://github.com/fhempy/fhempy/assets/100911185/055f1a09-2e02-4d62-adc8-e8f8346f91e3)


Fhemp local says connection denied:
![image](https://github.com/fhempy/fhempy/assets/100911185/3be9d4e3-98ae-439e-86d1-9574a2ed2289)

Do you have any idea why the fhempy server stopped?

**Comment by fhempy** [comment]
Log file please.

**Comment by maartenvullings** [comment]
Now I continuously get this:

FHEM/bindings/python/bin/fhempy: regel 9: cd: HOME is niet gedefinieerd
Activating virtual environment...OK
2024-01-12 16:24:18,004 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.698...
2024-01-12 16:24:18,007 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2024-01-12 16:24:18,074 - ERROR    - fhempy.lib.fhem_pythonbinding: Another instance of fhempy is running, stop the other instance first.
2024-01-12 16:24:18,075 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 0
FHEM/bindings/python/bin/fhempy: regel 9: cd: HOME is niet gedefinieerd
Activating virtual environment...OK
2024-01-12 16:24:40,003 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.698...
2024-01-12 16:24:40,006 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
2024-01-12 16:24:40,072 - ERROR    - fhempy.lib.fhem_pythonbinding: Another instance of fhempy is running, stop the other instance first.
2024-01-12 16:24:40,073 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 0

**Comment by maartenvullings** [comment]
I deleted fhempy local and fhempy server. Then reinstalled it but I still get these messages in the log file...

**Comment by fhempy** [comment]
HOME is not defined, which user starts fhempy? Please make sure that the HOME environment variable is set on your system.
